title: Yourname's Homepage
page-top-title: YiHeng Zhang
page-top-subtitle: Welcome to my personal website
home-subtitle: YiHeng Zhang
copyright-text: '&copy; YiHeng Zhang 2023-2025. All Rights Reserved.'
